In [1]:
import pandas as pd

In [8]:
s1_usage_k9 = pd.read_csv('all_datasets_consensus/anal_pc5_c21_S1.filtered_consensus_outputs/anal_pc5_c21_S1.filtered.usages.k_9.dt_0_01.consensus.txt', sep='\t')
s1_usage_k9.rename(columns={'Unnamed: 0':'cell_name'}, inplace=True)
s1_usage_k9.head()

,cell_name,1,2,3,4,5,6,7,8,9
0,S1_AAACAAGCAACAGCACACTTTAGG_anal_34449_1_1,17.442671,522.653043,14.010166,0.00000,0.000000,0.000000,0.000000,0.000000,0.0
1,S1_AAACAAGCAATTGAGTACTTTAGG_anal_34449_1_1,183.533985,0.000000,0.000000,0.00000,0.000000,532.500312,735.522510,0.000000,0.0
2,S1_AAACAAGCACGTAAATACTTTAGG_anal_34449_1_1,53.141684,475.912804,26.030644,0.00000,419.872205,0.000000,3.456642,25.738547,0.0
3,S1_AAACAAGCACTATCACACTTTAGG_anal_34449_1_1,0.000000,0.000000,0.000000,196.50764,0.000000,0.000000,0.000000,0.000000,0.0
4,S1_AAACAAGCAGAATGAAACTTTAGG_anal_34449_1_1,0.000000,0.000000,0.000000,0.00000,0.000000,3.951487,0.000000,1928.603975,0.0

In [10]:
metadata = pd.read_csv('data/anal_cancer_n21_meta.csv')
metadata.rename(columns={'Unnamed: 0':'cell_name'}, inplace=True)
metadata.head()

/tmp/ipykernel_52488/1495593758.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv('data/anal_cancer_n21_meta.csv')

,cell_name,samplename,viral_status,cluster_annot,copykat,pathology_status,cluster_annot2,cluster_annot3
0,S1_AAACAAGCAACAGCACACTTTAGG_anal_34449_1_1,S1_Sanal_34449,HPV-_HIV+,T_cells,not.defined,cancer,CD4+Tcells,Tregs
1,S1_AAACAAGCAATTGAGTACTTTAGG_anal_34449_1_1,S1_Sanal_34449,HPV-_HIV+,Myeloid_cells,diploid,cancer,DC_CLEC9A,DC_CLEC9A
2,S1_AAACAAGCACGTAAATACTTTAGG_anal_34449_1_1,S1_Sanal_34449,HPV-_HIV+,Fibroblast_stromal,not.defined,cancer,CD8+Tcells,Fibroblasts/Stromal
3,S1_AAACAAGCACTATCACACTTTAGG_anal_34449_1_1,S1_Sanal_34449,HPV-_HIV+,B_cells,not.defined,cancer,Plasma_XBP1,Plasma_XBP1
4,S1_AAACAAGCAGAATGAAACTTTAGG_anal_34449_1_1,S1_Sanal_34449,HPV-_HIV+,Endothelials,diploid,cancer,Endothelials,Endothelials

In [12]:
usage_k9_metadata = s1_usage_k9.merge(metadata[['cell_name', 'cluster_annot3']], on='cell_name', how='left')
usage_k9_metadata

,cell_name,1,2,3,4,5,6,7,8,9,cluster_annot3
0,S1_AAACAAGCAACAGCACACTTTAGG_anal_34449_1_1,17.442671,522.653043,14.010166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Tregs
1,S1_AAACAAGCAATTGAGTACTTTAGG_anal_34449_1_1,183.533985,0.000000,0.000000,0.000000,0.000000,532.500312,735.522510,0.000000,0.000000,DC_CLEC9A
2,S1_AAACAAGCACGTAAATACTTTAGG_anal_34449_1_1,53.141684,475.912804,26.030644,0.000000,419.872205,0.000000,3.456642,25.738547,0.000000,Fibroblasts/Stromal
3,S1_AAACAAGCACTATCACACTTTAGG_anal_34449_1_1,0.000000,0.000000,0.000000,196.507640,0.000000,0.000000,0.000000,0.000000,0.000000,Plasma_XBP1
4,S1_AAACAAGCAGAATGAAACTTTAGG_anal_34449_1_1,0.000000,0.000000,0.000000,0.000000,0.000000,3.951487,0.000000,1928.603975,0.000000,Endothelials
...,...,...,...,...,...,...,...,...,...,...,...
14128,S1_TTTGTGAGTATGTGAGACTTTAGG_anal_34449_1_1,783.872440,380.247815,38.140952,20.791695,0.000000,0.000000,18.529850,0.000000,49.027592,Tumor/Epithelials
14129,S1_TTTGTGAGTCATGCATACTTTAGG_anal_34449_1_1,64.027264,16.732039,35.736079,174.482448,40.491753,322.687340,34.895054,0.000000,19.347739,Bcells_CD19
14130,S1_TTTGTGAGTTAGCATCACTTTAGG_anal_34449_1_1,20.722500,14.316517,64.866433,4.954759,17.749856,453.955854,0.000000,0.000000,0.000000,Bcells_CD19
14131,S1_TTTGTGAGTTGTTTGAACTTTAGG_anal_34449_1_1,494.011918,3.633199,21.250954,0.000000,0.000000,24.836531,0.000000,20.828226,0.000000,Tumor/Epithelials
14132,S1_TTTGTGAGTTTGTAGCACTTTAGG_anal_34449_1_1,86.823659,115.927126,10.927549,9.237550,652.201905,0.000000,0.000000,101.167710,0.000000,Fibroblasts/Stromal

In [14]:
usage_k9_metadata.columns

Index(['cell_name', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       'cluster_annot3'],
      dtype='object')

In [16]:
usage_k9_metadata.groupby('cluster_annot3')['6'].mean().sort_values(ascending=False)

cluster_annot3
Bcells_CD19            531.186597
pDCs                   440.623536
DC_CLEC9A              344.719273
DC_LAMP3               341.984937
DC_CD207               191.173953
Mast                    85.680373
Mon_VCAN                42.836200
Fibroblasts/Stromal     23.786984
Tumor/Epithelials       17.449839
Mac_C1Q_ZEB2            16.570988
Endothelials            16.173735
Neutrophils             12.404840
CD8+Tcells_Ki67          3.069147
Plasma_XBP1              0.868851
CD8+Tcells               0.687447
NKcells                  0.048016
CD4+Tcells               0.041258
Mac_C1Q_SPP1             0.000000
Tregs                    0.000000
Name: 6, dtype: float64